-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 22:11:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_employees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_employees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_employees` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_employees` ;

-- -----------------------------------------------------
-- Table `db_employees`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_employees`.`genders` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_employees`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_employees`.`jobs` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `SALARY` DECIMAL(9,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_employees`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_employees`.`employees` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GENDER_ID` INT NULL DEFAULT NULL,
  `JOB_ID` INT NULL DEFAULT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `BIRTHDAY` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`GENDER_ID` ASC) VISIBLE,
  INDEX `JOB_ID_idx` (`JOB_ID` ASC) VISIBLE,
  CONSTRAINT `GENDER_ID`
    FOREIGN KEY (`GENDER_ID`)
    REFERENCES `db_employees`.`genders` (`ID`),
  CONSTRAINT `JOB_ID`
    FOREIGN KEY (`JOB_ID`)
    REFERENCES `db_employees`.`jobs` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_employees`.`employee_worked_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_employees`.`employee_worked_hours` (
  `ID` INT NOT NULL,
  `EMPLOYEE_ID` INT NULL DEFAULT NULL,
  `WORKED_HOURS` DECIMAL(4,2) NULL DEFAULT NULL,
  `WORKED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `EMPLOYEE_ID_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_ID`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `db_employees`.`employees` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
